load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "twoSum",
    srcs = ["00001.twoSum.cpp"],
)

cc_binary(
    name = "addTwoNumbers",
    srcs = ["00002.addTwoNumbers.cpp"],
)

cc_binary(
    name = "lengthOfLongestSubstring",
    srcs = ["00003.lengthOfLongestSubstring.cpp"],
)

cc_binary(
    name = "findMedianSortedArrays",
    srcs = ["00004.findMedianSortedArrays.cpp"],
)

cc_binary(
    name = "longestPalindrome",
    srcs = ["00005.longestPalindrome.cpp"],
)

cc_binary(
    name = "convert",
    srcs = ["00006.convert.cpp"],
)

cc_binary(
    name = "reverse",
    srcs = ["00007.reverse.cpp"],
)

cc_binary(
    name = "myAtoi",
    srcs = ["00008.myAtoi.cpp"],
)

cc_binary(
    name = "isPalindrome",
    srcs = ["00009.isPalindrome.cpp"],
)

cc_binary(
    name = "isMatch",
    srcs = ["00010.isMatch.cpp"],
)

cc_binary(
    name = "maxArea",
    srcs = ["00011.maxArea.cpp"],
)

cc_binary(
    name = "removeNthFromEnd",
    srcs = ["00019.removeNthFromEnd.cpp"],
)

cc_binary(
    name = "mergeTwoLists",
    srcs = ["00021.mergeTwoLists.cpp"],
)

cc_binary(
    name = "searchInsert",
    srcs = ["00035.searchInsert.cpp"],
)

cc_binary(
    name = "connect",
    srcs = ["00116.connect.cpp"],
)

cc_binary(
    name = "rotate",
    srcs = ["00189.rotate.cpp"],
)

cc_binary(
    name = "reverseList",
    srcs = ["00206.reverseList.cpp"],
)

cc_binary(
    name = "moveZeroes",
    srcs = ["00283.moveZeroes.cpp"],
)

cc_binary(
    name = "reverseString",
    srcs = ["00344.reverseString.cpp"],
)

cc_binary(
    name = "updateMatrix",
    srcs = ["00542.updateMatrix.cpp"],
)

cc_binary(
    name = "reverseWords",
    srcs = ["00557.reverseWords.cpp"],
)

cc_binary(
    name = "checkInclusion",
    srcs = ["00567.checkInclusion.cpp"],
)

cc_binary(
    name = "maxAreaOfIsland",
    srcs = ["00695.maxAreaOfIsland.cpp"],
)

cc_binary(
    name = "floodFill",
    srcs = ["00733.floodFill.cpp"],
)

cc_binary(
    name = "middleNode",
    srcs = ["00876.middleNode.cpp"],
)

cc_binary(
    name = "sortedSquares",
    srcs = ["00977.sortedSquares.cpp"],
)
