load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "searchInsert",
    srcs = ["searchInsert.cpp"],
)

cc_binary(
    name = "sortedSquares",
    srcs = ["sortedSquares.cpp"],
)

cc_binary(
    name = "rotate",
    srcs = ["rotate.cpp"],
)

cc_binary(
    name = "moveZeroes",
    srcs = ["moveZeroes.cpp"],
)