load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "searchInsert",
    srcs = ["searchInsert.cpp"],
)

cc_binary(
    name = "sortedSquares",
    srcs = ["sortedSquares.cpp"],
)

cc_binary(
    name = "rotate",
    srcs = ["rotate.cpp"],
)

cc_binary(
    name = "moveZeroes",
    srcs = ["moveZeroes.cpp"],
)

cc_binary(
    name = "twoSum",
    srcs = ["twoSum.cpp"],
)

cc_binary(
    name = "reverseString",
    srcs = ["reverseString.cpp"],
)

cc_binary(
    name = "reverseWords",
    srcs = ["reverseWords.cpp"],
)

cc_binary(
    name = "middleNode",
    srcs = ["middleNode.cpp"],
)

cc_binary(
    name = "removeNthFromEnd",
    srcs = ["removeNthFromEnd.cpp"],
)

cc_binary(
    name = "lengthOfLongestSubstring",
    srcs = ["lengthOfLongestSubstring.cpp"],
)

cc_binary(
    name = "checkInclusion",
    srcs = ["checkInclusion.cpp"],
)

cc_binary(
    name = "floodFill",
    srcs = ["floodFill.cpp"],
)

cc_binary(
    name = "maxAreaOfIsland",
    srcs = ["maxAreaOfIsland.cpp"],
)

cc_binary(
    name = "connect",
    srcs = ["connect.cpp"],
)

cc_binary(
    name = "mergeTwoLists",
    srcs = ["mergeTwoLists.cpp"],
)

cc_binary(
    name = "reverseList",
    srcs = ["reverseList.cpp"],
)

cc_binary(
    name = "updateMatrix",
    srcs = ["updateMatrix.cpp"],
)

cc_binary(
    name = "addTwoNumbers",
    srcs = ["addTwoNumbers.cpp"],
)

cc_binary(
    name = "findMedianSortedArrays",
    srcs = ["findMedianSortedArrays.cpp"],
)

cc_binary(
    name = "longestPalindrome",
    srcs = ["longestPalindrome.cpp"],
)

cc_binary(
    name = "convert",
    srcs = ["convert.cpp"],
)

cc_binary(
    name = "reverse",
    srcs = ["reverse.cpp"],
 )

cc_binary(
    name = "myAtoi",
    srcs = ["myAtoi.cpp"],
 )