load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "searchInsert",
    srcs = ["searchInsert.cpp"],
)

cc_binary(
    name = "sortedSquares",
    srcs = ["sortedSquares.cpp"],
)

cc_binary(
    name = "rotate",
    srcs = ["rotate.cpp"],
)

cc_binary(
    name = "moveZeroes",
    srcs = ["moveZeroes.cpp"],
)

cc_binary(
    name = "twoSum",
    srcs = ["twoSum.cpp"],
)

cc_binary(
    name = "reverseString",
    srcs = ["reverseString.cpp"],
)

cc_binary(
    name = "reverseWords",
    srcs = ["reverseWords.cpp"],
)

cc_binary(
    name = "middleNode",
    srcs = ["middleNode.cpp"],
)

cc_binary(
    name = "removeNthFromEnd",
    srcs = ["removeNthFromEnd.cpp"],
)

cc_binary(
    name = "lengthOfLongestSubstring",
    srcs = ["lengthOfLongestSubstring.cpp"],
)