* Spacemacs Rocks Episode 2 (Day tow)

** Fixed some annoying stuff?
1. make cursor style to bar
2. disable backup file
#+BEGIN_SRC emacs-lisp
  (setq make-backup-files nil)
#+END_SRC
use C-' to open another buffer to edit source code.
Make source code fancy in the org file.
#+BEGIN_SRC emacs-lisp
  (require 'org)
  (setq org-src-fontify-natively t)
#+END_SRC

3. enable recentf-mode
#+BEGIN_SRC emacs-lisp
  (require 'recentf)
  (recentf-mode 1)
  (setq recentf-max-menu-items 25)
  (global-set-key "\C-x\ \C-r" 'recentf-open-files)
#+END_SRC

4. bring electric-indent-mode back

5. add delete selection mode
#+BEGIN_SRC emacs-lisp
  (delete-selection-mode t)
#+END_SRC

** Make emacs more fancy
1. open with full screen
#+BEGIN_SRC emacs-lisp
  (setq initial-frame-alist (quote(fullscreen . maximized)))
#+END_SRC

2. show match parents
#+BEGIN_SRC emacs-lisp
  (add-hook 'emacs-lisp-mode-hok 'show-paren-mode)
#+END_SRC
Is has a flaw, we will use more powerful package the feature

3. Heightlight current line (global-hl-line-mode)
#+BEGIN_SRC emacs-lisp
  (global-hl-line-mode t)
#+END_SRC

** Improve built-in package system
1. make package system more powerful with Melpa
#+BEGIN_SRC emacs-lisp
  (when (>= emacs-major-version 24)
    (require 'package)
    (package-initialize)
    (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t))
  (require 'cl)

  ;; add whatever package you want here
  (defvar sunday/packages '(
                            company
                            ) "Default packages")

  (defun sunday/package-initialize-p ()
    (loop for pkg in sunday/packages
          when (not (package-initialize-p pkg)) do (return nil)
          finally (return t)))

  (unless (sunday/package-iniialize-p)
    (message "%s" "Refreshing package database...")
    (package-refresh-contents)
    (dolist (pkg sunday/packages)
      (when (not (package-initialize-p pkg))
        (package-install pkg)
#+END_SRC

1. install a theme (monokai)
2. install hungry delete mode
3. package-list-packages (add/delete/update packages)
4. install and configure semx and ivy mode
5. use customize-group to customize the package settings 
6. install and configure smartparens mode
7. Don't try to update the package daily, the updating process might failed.

(tips: press M-RET to fix the order, you could also use M-RET to add new headings, cheers!)

** Setup a javascript IDE
1. Install js2-mode and start to write javascript
2. Install nodejs-repl to execute code install Emacs

** Learn more from Emacs itself
1. c-h c-f(find-function), c-h c-v(find-veriable), c-h c-k(find-function-on-key)
2. Tell users to lean more about elisp(M-x info)

